services:
  postgres:
    image: postgres:16
    container_name: ldp-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: shop
    command: ["postgres", "-c", "wal_level=logical"]
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.9.0
    container_name: ldp-kafka
    ports:
      - "127.0.0.1:9092:9092"

volumes:
  pgdata:
